name: Snake game

on:
  schedule: # executar a cada 12 horas
    - cron: "*/12 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Atualizar dados
    runs-on: ubuntu-latest
    steps:
      # Animação da Cobrinha
      - uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: QueijoQualho
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
